### ISSUE TITLE
Carpeta de imagenes por usuario

### ISSUE THREAD

**Issue by Drascor** [nethruster/nethloader#4]
Que cada usuario tenga su propia carpeta de imagenes, de cara a poder tener un control mejor en el servidor.

**Comment by claudio4** [comment]
Era algo que ya estábamos barajando, seguramente lo integremos en la 2.0.

**Comment by claudio4** [comment]
La función se ha añadido por completo en el commit a9f154ed388dbdcb3f69409910d23c77d065a87f
