### ISSUE TITLE
Cifrado en servidor

### ISSUE THREAD

**Issue by Drascor** [nethruster/nethloader#7]
Cifrar el contenido en servidor para garantizar privacidad a los usuarios.

**Comment by gariasf** [comment]
Drascor,hemos hablado sobre el tema y hemos visto que la utilidad de una caracteristica como esta  aplica si almacenas los archivos en un sitio externo como google drive o similar donde es relativamente sencillo que otras personas ganen acceso. 
Por otro lado, simplemente no vemos la necesidad de implementar cifrado.
